# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.28.2-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.28.2-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/malte/code/simpleClai

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/malte/code/simpleClai

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/cmake-3.28.2-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.28.2-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/cmake-3.28.2-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/cmake-3.28.2-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/cmake-3.28.2-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/cmake-3.28.2-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/cmake-3.28.2-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/cmake-3.28.2-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/malte/code/simpleClai/CMakeFiles /home/malte/code/simpleClai//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/malte/code/simpleClai/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sclai

# Build rule for target.
sclai: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sclai
.PHONY : sclai

# fast build rule for target.
sclai/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/build
.PHONY : sclai/fast

#=============================================================================
# Target rules for targets named ClParser

# Build rule for target.
ClParser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ClParser
.PHONY : ClParser

# fast build rule for target.
ClParser/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/CMakeFiles/ClParser.dir/build.make external/ClParser/CMakeFiles/ClParser.dir/build
.PHONY : ClParser/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/Experimental.dir/build.make external/ClParser/tests/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/Nightly.dir/build.make external/ClParser/tests/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/Continuous.dir/build.make external/ClParser/tests/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/NightlyMemoryCheck.dir/build.make external/ClParser/tests/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/NightlyStart.dir/build.make external/ClParser/tests/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/NightlyUpdate.dir/build.make external/ClParser/tests/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/NightlyConfigure.dir/build.make external/ClParser/tests/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/NightlyBuild.dir/build.make external/ClParser/tests/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/NightlyTest.dir/build.make external/ClParser/tests/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/NightlyCoverage.dir/build.make external/ClParser/tests/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/NightlyMemCheck.dir/build.make external/ClParser/tests/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/NightlySubmit.dir/build.make external/ClParser/tests/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/ExperimentalStart.dir/build.make external/ClParser/tests/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/ExperimentalUpdate.dir/build.make external/ClParser/tests/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/ExperimentalConfigure.dir/build.make external/ClParser/tests/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/ExperimentalBuild.dir/build.make external/ClParser/tests/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/ExperimentalTest.dir/build.make external/ClParser/tests/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/ExperimentalCoverage.dir/build.make external/ClParser/tests/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/ExperimentalMemCheck.dir/build.make external/ClParser/tests/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/ExperimentalSubmit.dir/build.make external/ClParser/tests/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/ContinuousStart.dir/build.make external/ClParser/tests/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/ContinuousUpdate.dir/build.make external/ClParser/tests/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/ContinuousConfigure.dir/build.make external/ClParser/tests/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/ContinuousBuild.dir/build.make external/ClParser/tests/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/ContinuousTest.dir/build.make external/ClParser/tests/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/ContinuousCoverage.dir/build.make external/ClParser/tests/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/ContinuousMemCheck.dir/build.make external/ClParser/tests/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/ContinuousSubmit.dir/build.make external/ClParser/tests/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f external/ClParser/tests/CMakeFiles/test.dir/build.make external/ClParser/tests/CMakeFiles/test.dir/build
.PHONY : test/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/main.cpp.s
.PHONY : main.cpp.s

src/commands/dataset.o: src/commands/dataset.cpp.o
.PHONY : src/commands/dataset.o

# target to build an object file
src/commands/dataset.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/commands/dataset.cpp.o
.PHONY : src/commands/dataset.cpp.o

src/commands/dataset.i: src/commands/dataset.cpp.i
.PHONY : src/commands/dataset.i

# target to preprocess a source file
src/commands/dataset.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/commands/dataset.cpp.i
.PHONY : src/commands/dataset.cpp.i

src/commands/dataset.s: src/commands/dataset.cpp.s
.PHONY : src/commands/dataset.s

# target to generate assembly for a file
src/commands/dataset.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/commands/dataset.cpp.s
.PHONY : src/commands/dataset.cpp.s

src/commands/frameworks.o: src/commands/frameworks.cpp.o
.PHONY : src/commands/frameworks.o

# target to build an object file
src/commands/frameworks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/commands/frameworks.cpp.o
.PHONY : src/commands/frameworks.cpp.o

src/commands/frameworks.i: src/commands/frameworks.cpp.i
.PHONY : src/commands/frameworks.i

# target to preprocess a source file
src/commands/frameworks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/commands/frameworks.cpp.i
.PHONY : src/commands/frameworks.cpp.i

src/commands/frameworks.s: src/commands/frameworks.cpp.s
.PHONY : src/commands/frameworks.s

# target to generate assembly for a file
src/commands/frameworks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/commands/frameworks.cpp.s
.PHONY : src/commands/frameworks.cpp.s

src/commands/model.o: src/commands/model.cpp.o
.PHONY : src/commands/model.o

# target to build an object file
src/commands/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/commands/model.cpp.o
.PHONY : src/commands/model.cpp.o

src/commands/model.i: src/commands/model.cpp.i
.PHONY : src/commands/model.i

# target to preprocess a source file
src/commands/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/commands/model.cpp.i
.PHONY : src/commands/model.cpp.i

src/commands/model.s: src/commands/model.cpp.s
.PHONY : src/commands/model.s

# target to generate assembly for a file
src/commands/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/commands/model.cpp.s
.PHONY : src/commands/model.cpp.s

src/commands/profile.o: src/commands/profile.cpp.o
.PHONY : src/commands/profile.o

# target to build an object file
src/commands/profile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/commands/profile.cpp.o
.PHONY : src/commands/profile.cpp.o

src/commands/profile.i: src/commands/profile.cpp.i
.PHONY : src/commands/profile.i

# target to preprocess a source file
src/commands/profile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/commands/profile.cpp.i
.PHONY : src/commands/profile.cpp.i

src/commands/profile.s: src/commands/profile.cpp.s
.PHONY : src/commands/profile.s

# target to generate assembly for a file
src/commands/profile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/commands/profile.cpp.s
.PHONY : src/commands/profile.cpp.s

src/commands/project.o: src/commands/project.cpp.o
.PHONY : src/commands/project.o

# target to build an object file
src/commands/project.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/commands/project.cpp.o
.PHONY : src/commands/project.cpp.o

src/commands/project.i: src/commands/project.cpp.i
.PHONY : src/commands/project.i

# target to preprocess a source file
src/commands/project.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/commands/project.cpp.i
.PHONY : src/commands/project.cpp.i

src/commands/project.s: src/commands/project.cpp.s
.PHONY : src/commands/project.s

# target to generate assembly for a file
src/commands/project.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/commands/project.cpp.s
.PHONY : src/commands/project.cpp.s

src/core/parser.o: src/core/parser.cpp.o
.PHONY : src/core/parser.o

# target to build an object file
src/core/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/core/parser.cpp.o
.PHONY : src/core/parser.cpp.o

src/core/parser.i: src/core/parser.cpp.i
.PHONY : src/core/parser.i

# target to preprocess a source file
src/core/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/core/parser.cpp.i
.PHONY : src/core/parser.cpp.i

src/core/parser.s: src/core/parser.cpp.s
.PHONY : src/core/parser.s

# target to generate assembly for a file
src/core/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/core/parser.cpp.s
.PHONY : src/core/parser.cpp.s

src/utils/errors.o: src/utils/errors.cpp.o
.PHONY : src/utils/errors.o

# target to build an object file
src/utils/errors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/utils/errors.cpp.o
.PHONY : src/utils/errors.cpp.o

src/utils/errors.i: src/utils/errors.cpp.i
.PHONY : src/utils/errors.i

# target to preprocess a source file
src/utils/errors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/utils/errors.cpp.i
.PHONY : src/utils/errors.cpp.i

src/utils/errors.s: src/utils/errors.cpp.s
.PHONY : src/utils/errors.s

# target to generate assembly for a file
src/utils/errors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/utils/errors.cpp.s
.PHONY : src/utils/errors.cpp.s

src/utils/tools.o: src/utils/tools.cpp.o
.PHONY : src/utils/tools.o

# target to build an object file
src/utils/tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/utils/tools.cpp.o
.PHONY : src/utils/tools.cpp.o

src/utils/tools.i: src/utils/tools.cpp.i
.PHONY : src/utils/tools.i

# target to preprocess a source file
src/utils/tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/utils/tools.cpp.i
.PHONY : src/utils/tools.cpp.i

src/utils/tools.s: src/utils/tools.cpp.s
.PHONY : src/utils/tools.s

# target to generate assembly for a file
src/utils/tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sclai.dir/build.make CMakeFiles/sclai.dir/src/utils/tools.cpp.s
.PHONY : src/utils/tools.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... ClParser"
	@echo "... sclai"
	@echo "... test"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/commands/dataset.o"
	@echo "... src/commands/dataset.i"
	@echo "... src/commands/dataset.s"
	@echo "... src/commands/frameworks.o"
	@echo "... src/commands/frameworks.i"
	@echo "... src/commands/frameworks.s"
	@echo "... src/commands/model.o"
	@echo "... src/commands/model.i"
	@echo "... src/commands/model.s"
	@echo "... src/commands/profile.o"
	@echo "... src/commands/profile.i"
	@echo "... src/commands/profile.s"
	@echo "... src/commands/project.o"
	@echo "... src/commands/project.i"
	@echo "... src/commands/project.s"
	@echo "... src/core/parser.o"
	@echo "... src/core/parser.i"
	@echo "... src/core/parser.s"
	@echo "... src/utils/errors.o"
	@echo "... src/utils/errors.i"
	@echo "... src/utils/errors.s"
	@echo "... src/utils/tools.o"
	@echo "... src/utils/tools.i"
	@echo "... src/utils/tools.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

